# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AdaptiveRadiusCapacity
                                 A QGIS plugin
 AdaptiveRadiusCapacity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-17
        copyright            : (C) 2026 by ALXB
        email                : alexlepe@mit.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'ALXB'
__date__ = '2026-03-17'
__copyright__ = '(C) 2026 by ALXB'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .AdaptiveRadiusCapacity_provider import AdaptiveRadiusCapacityProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class AdaptiveRadiusCapacityPlugin(object):
    def __init__(self):
        self.provider = None

    def initProcessing(self):
        self.provider = AdaptiveRadiusCapacityProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)



